---
symlinks:
  - { src: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport, dest: airport }
  - { src: "/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py", dest: join.py }

osx_defaults:
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    notify: "Restart Dock"

  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    notify: "Restart Dock"

  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    notify: "Restart Finder"
