---
- name: Change /usr/local owner to "{{ ansible_user_id }}"
  become: true
  become_method: sudo
  file:
    dest: /usr/local
    owner: "{{ ansible_user_id }}"
    group: admin
    recurse: yes
  when: not "{{ lookup('pipe', 'ls -ld /usr/local') }}" | search("ansible_user_id")

- name: Install homebrew
  shell: |
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item.tap }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ homebrew_cask_packages }}"

- name: Install homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default(omit) }}"
  with_items:
    - "{{ homebrew_packages }}"
