---
ansible_python_interpreter: /Users/knakayama/.pyenv/shims/python

homebrew_taps:
  - { name: caskroom/cask }
  - { name: homebrew/binary }
  - { name: homebrew/dupes }
  - { name: caskroom/fonts }
  - { name: caskroom/versions }
  - { name: sanemat/font }
  - { name: kevwil/patches }
  - { name: bfontaine/utils }
  - { name: yudai/gotty }
  - { name: caarlos0/antibody }

homebrew_packages:
  - { name: brew-cask }
  - { name: ghq, install_options: completions}
  - { name: pcre }
  - { name: libxml2 }
  - { name: glib }
  - { name: fontconfig }
  - { name: readline }
  - { name: openssl }
  - { name: python }
  - { name: coreutils }
  - { name: git }
  - { name: zsh, install_options: disable-etcdir }
  - { name: wget }
  - { name: curl }
  - { name: cmake }
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: ctags }
  - { name: tree }
  - { name: nkf }
  - { name: jq }
  - { name: go }
  - { name: direnv }
  - { name: peco }
  - { name: hub }
  - { name: rbenv }
  - { name: ruby-build }
  - { name: rbenv-binstubs }
  - { name: rbenv-gem-rehash }
  - { name: w3m }
  - { name: tmux }
  - { name: reattach-to-user-namespace }
  - { name: sha2 }
  - { name: xz }
  - { name: lua }
  - { name: vim, install_options: with-lua }
  - { name: rsense }
  - { name: pyenv }
  - { name: pyenv-virtualenv }
  - { name: plenv }
  - { name: perl-build }
  - { name: awscli }
  - { name: gpg }
  - { name: msmtp }
  - { name: getmail }
  - { name: abook }
  - { name: ripmime }
  - { name: urlview }
  - { name: weechat, install_options: "with-ruby, with-python, with-perl" }
  - { name: rfc }
  - { name: mobile-shell }
  - { name: xhyve }
  - { name: gotty }
  - { name: ricty }
  - { name: mutt, install_options: "with-sidebar-patch, with-confirm-attachement-patch, with-trash-patch" }
  - { name: npm }
  - { name: fpp }
  - { name: bash }
  - { name: antibody }

homebrew_cask_packages:
  - { name: avast }
  - { name: iterm2 }
  - { name: firefox }
  - { name: google-japanese-ime }
  - { name: java }
  - { name: karabiner }
  - { name: vagrant }
  - { name: virtualbox }
  - { name: kindle }
  - { name: xquartz }
  - { name: alfred }
  - { name: shiftit }
  - { name: gimp }
  - { name: terraform }
  - { name: packer }
  - { name: macvim }
  - { name: google-chrome }

pip_packages:
  - { name: flake8 }
  - { name: ipython }
  - { name: ansible_lint }
  - { name: ansible_shell }

gem_packages:
  - { name: rubocop }
  - { name: terminal-table }

npm_packages:
  - { name: http-console }

go_packages:
  - { name: github.com/bfontaine/httpdoc }

git_repositories:
  - { repo: "https://github.com/knakayama/credentials.git", dest: ~/.ghq/github.com/knakayama/credentials }
  - { repo: "git@github.com:knakayama/dotfiles.git", dest: ~/.ghq/github.com/knakayama/dotfiles }
  - { repo: "https://github.com/Shougo/neobundle.vim", dest: ~/.vim/bundle/neobundle.vim }
  - { repo: "https://github.com/tmux-plugins/tpm.git", dest: ~/.tmux/plugins/tpm }

go_packages:
  - { name: httpdoc, path: github.com/bfontaine/httpdoc }
